<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
p{
    color:red;
    background-color:blue;
}
body{
    color:red;
}




</style>



</head>
<body>
<label><p> first number</P> </label>
<input type="text">
<input type="button" value="gread"</input><br>
<input type= "button" value="submit"</input>

</body>
</html>